@startuml Cas d'utilisation (web)

"Utilisateur" as u << Personne >>
"Utilisateur Connecté" as uc << Personne >>
"Utilisateur Non Connecté" as unc << Personne >>

rectangle "Gestion des rendez-vous" {
    ("Créer un rendez-vous") as addR
    ("Récupérer un rendez-vous") as recR
    ("Modifier un rendez-vous") as modR
    ("Supprimer un rendez-vous") as suppR
}

' Relations entre les acteurs
u <|-- uc
u <|-- unc

' Relations des cas d'utilisation


uc -- addR
uc -- modR
uc -- suppR
uc -- recR



left to right direction
@enduml