@startuml Services
!include stylesPlantuml.puml

namespace services {
    class AgendaService {
        + AgendaService(daoFactory : DAOFactory)
        + createAgenda(createAgendaDTO: CreateAgendaRequestDTO): CreateAgendaResponseDTO
    }
}

services.AgendaService *-- daos.factory.DAOFactory

@enduml