@startuml Diagramme d'activité de la récupération d'un rendez-vous
title Récuperer un rendez-vous via l'API

|c|Client
|s|Serveur
|b|Support de stockage

|c|
start
:Faire une requête GET /rendez-vous/{id};

|s|
:Verifier l'authentification de l'utilisateur;
if (L'utilisateur est authentifié ?) then (non)
    :Envoyer une réponse d'erreur 401 Unauthorized au client;
else (oui)
    :Valider le format des données de récupération du rendez-vous;
    if (Les données sont valides ?) then (non)
        :Envoyer une réponse d'erreur 400 Bad Request au client;
    else (oui)
        |b|
        :Vérifier l'existence du rendez-vous;
        |s|
        if (Le rendez-vous existe ?) then (non)
            :Envoyer une réponse d'erreur 404 Not Found au client;
        else (oui)
            |b|
            :Récupérer le droit de l'utilisateur sur l'agenda associé au rendez-vous;
            |s|
            if (L'utilisateur a le droit de lire l'agenda ?) then (non)
                :Envoyer une réponse d'erreur 403 Forbidden au client;
            else (oui)
                |b|
                :Récupérer le rendez-vous dans le support de stockage;
                |s|
                if (Le rendez-vous est récupéré ?) then (non)
                    :Envoyer une réponse d'erreur 500 Internal Server Error au client;
                else (oui)
                    :Envoyer une réponse 200 avec le rendez-vous au client;
                endif
            endif
        endif
    endif
endif

stop
@enduml