x-common-setup:
  #   # image: mcr.microsoft.com/devcontainers/base:ubuntu
  &common-setup
  volumes:
    - ..:/workspace:cached
  command: sleep infinity

services:
  documentation:
    image: mcr.microsoft.com/devcontainers/base:bullseye
    <<: *common-setup
    network_mode: service:plantumlServer
    depends_on:
      - plantumlServer
    profiles: [ "doc" ]

  development:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-22-bookworm
    <<: *common-setup
    network_mode: service:mongodb
    depends_on:
      - mongodb
    profiles: [ "dev" ]

  plantumlServer:
    image: plantuml/plantuml-server:latest
    # restart: unless-stopped
    profiles: [ "doc" ]

  mongodb:
    image: mongo:latest
    # restart: unless-stopped
    profiles: [ "dev" ]
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
