@startuml Exceptions (classes pour des exceptions)

!include stylesPlantuml.puml

namespace exceptions {
    abstract Exception {
        - statusCode: Number
        - name: String
        - message: String
        - path: String
        - details: any
        - stack: String
        + Exception(statusCode: Number, name: String, message: String, path: String, details: any, stack: String)
        + getStatusCode(): Number
        + getName(): String
        + getMessage(): String
        + getPath(): String
        + getDetails(): any
        + getStack(): String
    }

    namespace validation {
        class ValidationException extends exceptions.Exception {
            + ValidationException(joiValidationError: ValidationError)
            + getStatusCode(): Number
            + getName(): String
            + getMessage(): String
            + getPath(): String
            + getDetails(): any
            + getStack(): String
        }
    }

    namespace daosFactory {
        abstract DAOFactoryException extends exceptions.Exception {
            + getName(): String
            + getMessage(): String
            + getPath(): String
            + getDetails(): any
            + getStack(): String
        }

        class DAOFactoryStartException extends DAOFactoryException {
            + getName(): String
            + getMessage(): String
            + getPath(): String
            + getDetails(): any
            + getStack(): String
        }

        class DAOFactoryStopException extends DAOFactoryException {
            + getName(): String
            + getMessage(): String
            + getPath(): String
            + getDetails(): any
            + getStack(): String
        }
    }

    namespace daos {
        class DAOException extends exceptions.Exception {
            + getStatusCode(): Number
            + getName(): String
            + getMessage(): String
            + getPath(): String
            + getDetails(): any
            + getStack(): String
        }
    }
}

@enduml