@startuml Mappers (permet de convertir entre les objets métier et les DTOs)
!include stylesPlantuml.puml

namespace mappers {
    interface Mapper {
        + toDTO(objetMetier: any): DTO
    }

    class CompteMapper {
        
    }

    class AgendaMapper {

    }

    class RendezVousMapper {

    }

    class RepetitionMapper {

    }

    Mapper ()- CompteMapper
    Mapper ()- AgendaMapper
    Mapper ()- RendezVousMapper
    Mapper ()- RepetitionMapper
}

mappers.Mapper --> modeles : "Reçoit"
mappers.Mapper --> dtos.DTO : "Renvoit"

@enduml