@startuml Utilitaires (classes pour des opérations utilitaires)

namespace utilitaires {
    interface Horloge {
        + dateActuelle(): Date
    }

    interface Hasheur {
        + hash(mot: String): String
    }
}

@enduml